name: Deploy AWS S3

on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 14.x

      - name: Install website dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          single-commit: true
